swagger: "2.0"
info:
  version: 0.0.1
  title: JSBIS Services
  description: API services for JSCBIS
basePath: "/api"
tags:
- name: "Label"
paths:
  /label/all:
    get:
      tags:
      - "Label"
      summary: "List labels"
      description: "Returns a list containing all labels"
      operationId: "findLabels"
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of labels"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Label"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /label/all/{typeid}:
    get:
      tags:
      - "Label"
      summary: "List labels by type"
      description: "Returns a list containing all labels of a type"
      operationId: "findLabelsByType"
      produces:
      - "application/json"
      parameters:
      - name: "typeid"
        in: "path"
        required: false
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "A list of labels by type"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Label"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /label/add/{typeid}/{name}/{abbr}:
    get:
      tags:
      - "Label"
      summary: "Creates a label"
      description: "Adds a new label to the label list. Returns the label."
      operationId: "addLabel"
      produces:
      - "application/json"
      parameters:
      - name: "typeid"
        in: "path"
        required: false
        type: "integer"
        format: "int64"
      - name: "name"
        in: "path"
        required: false
        type: "string"
      - name: "abbr"
        in: "path"
        required: false
        type: "string"
        schema:
          $ref: "#/definitions/Label"
      responses:
        201:
          description: "A Label succesfully created."
          schema:
            $ref: "#/definitions/Label"
        400:
          description: "A label couldn't be created."
        500:
          description: "An unexpected error occured."
        403:
          description: "A Insufficient permissions response"
  /label/add:
    post:
      tags:
      - "Label"
      summary: "Upload a new Label"
      description: "Upload a label"
      operationId: "uploadLabel"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Label"
      responses:
        200:
          description: "A label succesfully created."
          schema:
            $ref: "#/definitions/Label"
        400:
          description: "A label couldn't have been created."
        500:
          description: "An unexpected error occured."
        403:
          description: "A Insufficient permissions response"
definitions:
  Label:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      labeltypeid:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      abbr:
        type: "string"
      desc:
        type: "string"
