swagger: "2.0"
info:
  version: 0.0.1
  title: JSBIS Services
  description: API services for JSCBIS
basePath: "/api"
tags:
- name: "LabelType"
- name: "Label"
- name: "Program"
paths:
  /lt/all:
    get:
      tags:
      - "LabelType"
      summary: "List labelTypes"
      description: "Returns a list containing all labelTypess"
      operationId: "findAll"
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of labelTypes"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/LabelType"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /lt/find/{id}:
    get:
      tags:
      - "LabelType"
      summary: "Get A labelType by id"
      description: "Returns a labelType with the given id"
      operationId: "find"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "A labelType"
          schema:
            $ref: "#/definitions/LabelType"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /lt/save:
    post:
      tags:
      - "LabelType"
      summary: "Upload a new LabelType"
      description: "Upload a LabelType"
      operationId: "save"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/LabelType"
      responses:
        200:
          description: "A LabelType succesfully created."
          schema:
            $ref: "#/definitions/LabelType"
        400:
          description: "A LabelType couldn't have been created."
        500:
          description: "An unexpected error occured."
        403:
          description: "A Insufficient permissions response"
  /label/all:
    get:
      tags:
      - "Label"
      summary: "List labels"
      description: "Returns a list containing all labels"
      operationId: "findLabels"
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of labels"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Label"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /label/find/{id}:
    get:
      tags:
      - "Label"
      summary: "Get A label by id"
      description: "Returns a label with the given id"
      operationId: "find"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "A label by id"
          schema:
            items:
              $ref: "#/definitions/Label"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /label/type/{labelTypeId}:
    get:
      tags:
      - "Label"
      summary: "List labels by type"
      description: "Returns a list containing all labels of a type"
      operationId: "findByType"
      produces:
      - "application/json"
      parameters:
      - name: "labelTypeId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "A list of labels by type"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Label"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /label/save:
    post:
      tags:
      - "Label"
      summary: "Upload a new Label"
      description: "Upload a label"
      operationId: "save"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Label"
      responses:
        200:
          description: "A label succesfully created."
          schema:
            $ref: "#/definitions/Label"
        400:
          description: "A label couldn't have been created."
        500:
          description: "An unexpected error occured."
        403:
          description: "A Insufficient permissions response"
  /program/all:
    get:
      tags:
      - "Program"
      summary: "List of Programs"
      description: "Returns a list containing all Programs"
      operationId: "findAll"
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of Programs"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Program"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /program/find/{id}:
    get:
      tags:
      - "Program"
      summary: "Get A Program by id"
      description: "Returns a Program with the given id"
      operationId: "find"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "A Program by id"
          schema:
            items:
              $ref: "#/definitions/Program"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /program/save:
    post:
      tags:
      - "Program"
      summary: "Upload a new Program"
      description: "Upload a Program"
      operationId: "save"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Program"
      responses:
        200:
          description: "A Program succesfully created."
          schema:
            $ref: "#/definitions/Program"
        400:
          description: "A Program couldn't have been created."
        500:
          description: "An unexpected error occured."
        403:
          description: "A Insufficient permissions response"
definitions:
  LabelType:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      type:
        type: "string"
      descrption:
        type: "string"
  Label:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      labeltype:
        $ref: "#/definitions/LabelType"
      name:
        type: "string"
      abbr:
        type: "string"
      desc:
        type: "string"
  Program:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      programId:
        type: "string"
      programName:
        type: "string"
      poc:
        type: "string"
      programManager:
        type: "string"
      descr:
        type: "string"
      notes:
        type: "string"
      functionalArea:
        $ref: "#/definitions/Label"
      medicalCategory:
        $ref: "#/definitions/Label"
      nbcCategory:
        $ref: "#/definitions/Label"
      coreCapability:
        $ref: "#/definitions/Label"
      primaryCapability:
        $ref: "#/definitions/Label"
      secondaryCapability:
        $ref: "#/definitions/Label"
      tertiaryCapability:
        $ref: "#/definitions/Label"
