swagger: "2.0"
info:
  version: 0.0.1
  title: JSBIS Services
  description: API services for JSCBIS
basePath: "/api"
tags:
- name: "Tag"
- name: "Fund"
- name: "FundLine"
- name: "Increment"
- name: "Program"
paths:
  /blank:
    get:
      tags:
      - "blank"
      summary: ""
      description: ""
      operationId: "blank"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: "string"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /program/findall:
    get:
      tags:
      - "Program"
      summary: "List of Programs"
      description: "Returns a list containing all Programs"
      operationId: "findall"
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of Programs"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Program"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /fundLine/findall:
    get:
      tags:
      - "FundLine"
      summary: "List of FundLine"
      description: "Returns a list containing all FundLine"
      operationId: "findall"
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of FundLine"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/FundLine"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /fundLine/find/{id}:
    get:
      tags:
      - "FundLine"
      summary: "Get FundLine by Id"
      description: "Returns a FundLine with the given id"
      operationId: "find"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "A FundLine"
          schema:
            type: "FundLine"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"

  /tag/find/{type}:
    get:
      tags:
      - "Tag"
      summary: "Get Tags by type"
      description: "Returns a List of Tags with the given type"
      operationId: "findTagsByType"
      produces:
      - "application/json"
      parameters:
      - name: "type"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "A List of Tags"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tag"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
  /tag/findname/{name}:
    get:
      tags:
      - "Tag"
      summary: "Get Tags by name"
      description: "Returns a List of Tags with the given type"
      operationId: "findTagsByName"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "A List of Tags"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tag"
        500:
          description: "An unexpected error occured."
        403:
          description: "Forbidden/not authorized"
definitions:
  PexUser:
    type: "object"
    properties:
      password:
        type: "string"
      username:
        type: "string"
      accountNonExpired:
        type: "boolean"
      accountNonLocked:
        type: "boolean"
      credentialsNonExpired:
        type: "boolean"
      enabled:
        type: "boolean"
      firstName:
        type: "string"
      lastName:
        type: "string"
      cn:
        type: "string"
      organization:
        type: "string"
      communications:
        type: "array"
        items:
          $ref: '#/definitions/Communication'
      preferences:
        type: "object"
        additionalProperties:
            type: string
      authorities:
        type: "array"
        items:
          $ref: '#/definitions/GrantedAuthority'
  GrantedAuthority:
    type: "object"
    properties:
      authority:
        type: "string"
  Communication:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      type:
        type: "string"
        emun:
          - PHONE
          - EMAIL
      subtype:
        type: "string"
        emun:
          - PRIMARY
          - SECONDARY
          - ALTERNATE
      value:
        type: "string"
      confirmed:
        type: "boolean"
      preferred:
        type: "boolean"
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      type:
        type: "string"
      name:
        type: "string"
      abbr:
        type: "string"
  Fund:
    type: "object"
    properties:
      year:
        type: "integer"
      amount:
        type: "number"
        format: "float"
  FundLine:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      prgranId:
        type: "integer"
        format: "int64"
      incrementNumber:
        type: "integer"
      description:
        type: "string"
      fiscalYear:
        type: "integer"
      tags:
        type: "array"
        items:
          $ref: '#/definitions/Tag'
      funds:
        type: "array"
        items:
          $ref: '#/definitions/Fund'
  Increment:
    type: "object"
    properties:
      incrementNumber:
        type: "integer"
      description:
        type: "string"
      tags:
        type: "array"
        items:
          $ref: '#/definitions/Tag'
      fundingLineIds:
        type: "array"
        items:
          type: "integer"
          format: "int64"
  Program:
    Program:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      programId:
        type: "string"
      programName:
        type: "string"
      description:
        type: "string"
      tags:
        type: "array"
        items:
          $ref: '#/definitions/Tag'
      pocId:
        type: "array"
        items:
          type: "string"
      increments:
        type: "array"
        items:
          $ref: '#/definitions/Increment'
