export const enum Disposition {
  APPROVED = 'APPROVED',
  PARTIALLY_APPROVED = 'PARTIALLY_APPROVED',
  DISAPPROVED = 'DISAPPROVED',
  DEFERRED = 'DEFERRED',
  YEAR_OF_EXECUTION = 'YEAR_OF_EXECUTION',
  ISSUE_PAPER = 'ISSUE_PAPER'
}
