export const enum Disposition {
  APPROVED = 'APPROVED',
  PARTIALLY_APPROVED = 'PARTIALLY_APPROVED',
  DEFERRED_POM = 'DEFERRED_POM',
  DEFERRED_YOE = 'DEFERRED_YOE',
  DISAPPROVED = 'DISAPPROVED',
  DASD_REQUESTED = 'DASD_REQUESTED'
}
