export const enum PropertyType {
  WORK_UNIT_CODE = 'WORK_UNIT_CODE',
  EXPENDITURE_TYPE = 'EXPENDITURE_TYPE',
  SAG = 'SAG',
  BA_BLIN = 'BA_BLIN',
  APPROPRIATION = 'APPROPRIATION',
  DISPOSITION_TYPE = 'DISPOSITION_TYPE',
  OPERATING_AGENCY = 'OP_AGENCY',
  PROGRAM_ELEMENT = 'PROGRAM_ELEMENT_CODE'
}
