export const enum ShortyType {
  MRDB_PROGRAM = 'MRDB_PROGRAM',
  PR = 'PR',
  NEW_INCREMENT = 'NEW_INCREMENT',
  NEW_INCREMENT_FOR_MRDB_PROGRAM = 'NEW_INCREMENT_FOR_MRDB_PROGRAM',
  NEW_INCREMENT_FOR_PR = 'NEW_INCREMENT_FOR_PR',
  NEW_FOS = 'NEW_FOS',
  NEW_FOS_FOR_MRDB_PROGRAM = 'NEW_FOS_FOR_MRDB_PROGRAM',
  NEW_FOS_FOR_PR = 'NEW_FOS_FOR_PR',
  NEW_PROGRAM = 'NEW_PROGRAM'
}
