export const enum UFRStatus {
  SAVED = 'SAVED',
  OUTSTANDING = 'OUTSTANDING',
  SUBMITTED = 'SUBMITTED',
  VALID = 'VALID',
  INVALID = 'INVALID',
  WITHDRAWN = 'WITHDRAWN',
  ARCHIVED = 'ARCHIVED'
}
