export enum RoleConstants {

  POM_MANAGER = 'POM_MANAGER',
  BUDGET_MANAGER = 'BUDGET_MANAGER',
  FUNDS_REQUESTOR = 'FUNDS_REQUESTOR',
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  EXECUTION_MANAGER = 'EXECUTION_MANAGER',
  EXECUTION_REPORTER = 'EXECUTION_REPORTER',
  USER_APPROVER = 'USER_APPROVER',
  USER = 'USER',
  ORGANIZATION_MEMBER = 'ORGANIZATION_MEMBER'

}
