export const enum ExecutionImpact {
  CONGRESSIONAL_GENERAL_REDUCTIONS,
  CONGRESSIONAL_DIRECTED_REDUCTIONS,
  CONGRESSIONAL_RESCISSIONS,
  CONGRESSIONAL_ADDS,
  CONGRESSIONAL_DIRECTED_TRANSFERS,
  REPROGRAMMINGS,
  SBIR_STTR_TRANSFERS,
  OTHER_ADJUSTMENTS,
  NONE
}
